### ISSUE TITLE
Getting crash on 2.1.0 version

### ISSUE THREAD

**Issue by roworu** [SkyblockerMod/Skyblocker-modpack#3]
Getting crash on 2.1.0 version during launch on Prismlauncher:
Logs here: https://mclo.gs/rLzuYDE

**Comment by roworu** [comment]
I would guess, that is because of using old version of "EnhancedBlockEntities" mod -> 
enhancedblockentities-0.7.2+1.19.2
Disabling it solves the issue

**Comment by LifeIsAParadox** [comment]
Fixed with version 2.1.1 (a5cb293b93223d88fb0ffd953ff53b061fb025b9)
